version: '3.0'

expectations:
  population_size: 10000

actions:
             
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py
      --output output/dataset_definition.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_definition.csv 

  measures_dataset:
    run: ehrql:v1 generate-measures analysis/dataset_definition_measures.py
      --output output/measures/measures_dataset.csv
      --
      --start-date "2015-03-01"
      --intervals 96
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset.csv

  run_incidence_graphs:
    run: stata-mp:latest analysis/100_incidence_graphs.do
    needs: [measures_dataset]
    outputs:
      moderately_sensitive:
        log1: logs/descriptive_tables.log   
        figure1: output/figures/incidence_*.svg
        figure2: output/figures/prevalence_*.svg
        figure3: output/figures/inc_comp_*.svg
        figure4: output/figures/prev_comp_*.svg
        figure5: output/figures/inc_adj_*.svg
        figure6: output/figures/inc_ma_sex_*.svg
        figure7: output/figures/prev_adj_*.svg
        figure8: output/figures/inc_adj_ma_*.svg
        figure9: output/figures/inc_adj_ma2_*.svg
        figure10: output/figures/adj_ma_sex_*.svg
        figure11: output/figures/adj_ma_sex2_*.svg
        figure12: output/figures/adj_ma_age_*.svg
        data1: output/data/arima_nonstandardised.csv  

  run_sarima:
    run: r:latest analysis/200_sarima.R
    needs: [measures_dataset, run_incidence_graphs]
    outputs:
      moderately_sensitive:
        log1: logs/sarima_log.txt   
        figure1: output/figures/observed_*.svg
        figure2: output/figures/raw_pre_covid_*.svg
        figure3: output/figures/differenced_pre_covid_*.svg
        figure4: output/figures/seasonal_pre_covid_*.svg
        figure5: output/figures/raw_acf_*.svg
        figure6: output/figures/differenced_acf_*.svg
        figure7: output/figures/seasonal_acf_*.svg
        figure8: output/figures/auto_residuals_*.svg
        table1: output/tables/change_incidence_byyear.csv